spring:
  profiles:
    active:
    - dev
---
mybatis:
  mapper-locations:
  - classpath:mapping/*.xml
spring:
  datasource:
    url: jdbc:mysql://192.168.56.102:3306/springcloud-learn?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  application:
    name: product-provider
#  security:
#    user:
#      name: root
#      password: root
eureka:
  client:
    service-url:
      #      defaultZone: http://root:root@eureka1:7001/eureka
      defaultZone: http://root:root@eureka1:7001/eureka,http://root:root@eureka2:7002/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: product-provider:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）
info:
  app.name: springcloud-product-provider
  company.name: hjrpc
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
server:
  port: 8080
logging:
  level:
    com.hjrpc.mapper: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
server:
  port: 8081
mybatis:
  mapper-locations:
  - classpath:mapping/*.xml
spring:
  datasource:
    url: jdbc:mysql://192.168.56.102:3306/springcloud-learn?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  application:
    name: product-provider
#  security:
#    user:
#      name: root
#      password: root
eureka:
  client:
    service-url:
      #      defaultZone: http://root:root@eureka1:7001/eureka
      defaultZone: http://root:root@eureka1:7001/eureka,http://root:root@eureka2:7002/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: product-provider:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）
info:
  app.name: springcloud-product-provider
  company.name: hjrpc
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
logging:
  level:
    com.hjrpc.mapper: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'